# Generated by Django 5.2.4 on 2025-08-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['size']},
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
